openapi: 3.0.0
info:
  title: Kushagra IDP POC API Definition
  version: 1.0.0

paths:
  /message:
    get:
      summary: Get message
      responses:
        '200':
          description: OK

    post:
      summary: Create message
      requestBody:
        required: true
      responses:
        '200':
          description: Created

    put:
      summary: Update message
      requestBody:
        required: true
      responses:
        '200':
          description: Updated

    delete:
      summary: Delete message
      responses:
        '200':
          description: Deleted
